afkar_db_1:
  image: mysql:8
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: afkar
    MYSQL_PASSWORD: root


web:
  image: webappli
  ports:
    - "8080:8080"
  links:
    - afkar_db_1
